version=1.0.69
group=it.rebirthproject
author=Rebirth Project
authorWebsite=https://rebirth-project.it/
pluginWebsite=https://github.com/Rebirth-Project/rebirth-gradle-catalog-dependencies-monitor-plugin
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M "-XX:MaxMetaspaceSize=512m"
systemProp.org.gradle.internal.publish.checksums.insecure=true